version: '2'
services:
  web:
    build: .
    command: bin/rails server --port 8000 --binding 0.0.0.0
    volumes:
      - .:/theaterengine
      - bundle:/bundle
    ports:
      - '80:8000'
    env_file:
      - .theaterengine.env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: theaterengine
      POSTGRES_PASSWORD: theaterengine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch 
    environment:
      ES_JAVA_OPTS: "-Des.network.host=0.0.0.0 -Xmx1024m -Xms256m"

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/theaterengine
      - bundle:/bundle
    env_file:
      - .theaterengine.env

