theaterengine:
  extends:
    file: docker-common.yml
    service: web
  volumes_from:
    - bundle
  links:
    - postgres
    - redis
    - elasticsearch

postgres:
  extends:
    file: docker-common.yml
    service: postgres

redis:
  extends:
    file: docker-common.yml
    service: redis

elasticsearch:
  extends:
    file: docker-common.yml
    service: elasticsearch

bundle:
  extends:
    file: docker-common.yml
    service: bundle

sidekiq:
  extends:
    file: docker-common.yml
    service: sidekiq
  links:
    - postgres
    - redis

volumes:
  bundle: {}
  postgres: {}
  redis: {}
