theaterengine:
  build: .
  command: bin/rails server --port 8000 --binding 0.0.0.0
  links:
    - postgres
    - redis
    - elasticsearch
    - logstash
    - kibana
  volumes:
    - .:/theaterengine
  volumes_from:
    - bundle
  ports:
    - '80:8000'
  env_file:
    - .theaterengine.env


postgres:
  image: postgres:latest
  environment:
    POSTGRES_USER: theaterengine
    POSTGRES_PASSWORD: theaterengine
  ports:
    - '5432:5432'
  volumes:
    - theaterengine-postgres:/var/lib/postgresql/data

redis:
  image: redis:latest
  ports:
    - '6379:6379'
  volumes:
    - theaterengine-redis:/var/lib/redis/data

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0

logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  ports:
    - '12201:12201/udp'
  volumes:
    - './logstash:/etc/logstash/conf.d'
  links:
    - elasticsearch

kibana:
  image: kibana:latest
  links:
    - elasticsearch
  ports:
    - '5601:5601'
  volumes:
    - ./kibana/config/:/opt/kibana/config/

bundle:
  image: theaterengine_theaterengine
  volumes:
    - /bundle

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/theaterengine
  env_file:
    - .theaterengine.env
