version: '2'
services:
  theaterengine:
    extends:
      file: docker-common.yml
      service: web
    links:
      - postgres
      - redis
      - elasticsearch
    env_file:
      - .theaterengine.env


  postgres:
    extends:
      file: docker-common.yml
      service: postgres

  redis:
    extends:
      file: docker-common.yml
      service: redis

  elasticsearch:
    extends:
      file: docker-common.yml
      service: elasticsearch

  sidekiq:
    extends:
      file: docker-common.yml
      service: sidekiq
    links:
      - postgres
      - redis

volumes:
  bundle: {}
  postgres: {}
  redis: {}

