version: '2'
services:
  theaterengine:
    image: jhenahan/theaterengine:latest
    command: bin/rails server --port 8000 --binding 0.0.0.0
    extends:
      file: docker-common.yml
      service: web
    links:
      - postgres
      - redis
      - elasticsearch
      - logstash
      - kibana
    env_file:
      - .production.env
      - .logging.env


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=theaterengine
      - POSTGRES_PASSWORD=Kiyw9!BixeQapa
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    extends:
      file: docker-common.yml
      service: redis

  elasticsearch:
    environment:
      - JAVA_OPTS=-Xmx2048m -Xms256m
    extends:
      file: docker-common.yml
      service: elasticsearch

  sidekiq:
    image: jhenahan/theaterengine:latest
    extends:
      file: docker-common.yml
      service: sidekiq
    links:
      - postgres
      - redis

  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - '12201:12201/udp'
    volumes:
      - './logstash:/etc/logstash/conf.d'
    links:
      - elasticsearch

  kibana:
    image: kibana:latest
    links:
      - elasticsearch
    ports:
      - '5601:5601'
    volumes:
      - ./kibana/config/:/opt/kibana/config/

volumes:
  bundle: {}
  postgres: {}
  redis: {}
