development: &default
  adapter: postgresql
  database: TheaterEngine_development
  min_messages: WARNING
  pool: 5
  username: theaterengine
  host: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: TheaterEngine_test
